# findOrFailBy

The findOrFailBy method Allows you to pass custom attributes to locate a record by. If multiple records exist matching the conditions, only the first one found will be returned. If no record is found matching the conditions, a `RecordNotFound` exception is raised.

```ts
const user = await User.findOrFailBy({ email: 'abc' })
// User{email: 'abc'}
```

If findOrFailBy is called within a request cycle and the `RecordNotFound` exception is not handled manually, Psychic will automatically throw a 404.
